# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/biogo/hts
%global goipath         github.com/biogo/hts
Version:                1.4.3

%gometa

%global common_description %{expand:
Biogo high throughput sequencing repository.}

%global golicenses      LICENSE THIRD_PARTY_LICENSES/Gonum-LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Biogo high throughput sequencing repository

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
