# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/mitchellh/panicwrap
%global goipath         github.com/mitchellh/panicwrap
Version:                1.0.0

%gometa

%global common_description %{expand:
Panicwrap is a Go library for catching and handling panics in Go applications.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Panicwrap is a Go library for catching and handling panics in Go applications

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
