# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/hashicorp/hcp-sdk-go
%global goipath         github.com/hashicorp/hcp-sdk-go
Version:                0.16.0

%gometa

%global common_description %{expand:
Go SDK for HCP API.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go SDK for HCP API

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs CHANGELOG.md README.md

%gopkgfiles

%changelog
%autochangelog
