# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/hashicorp/packer-plugin-sdk
%global goipath         github.com/hashicorp/packer-plugin-sdk
Version:                0.2.11

%gometa

%global common_description %{expand:
Packer Plugin SDK enables building Packer plugins (builders, provisioners, or
post-processors) to manage any service providers or custom in-house solutions.}

%global golicenses      LICENSE multistep/LICENSE.md
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Packer Plugin SDK enables building Packer plugins (builders, provisioners, or post-processors) to manage any service providers or custom in-house solutions

# Upstream license specification: MPL-2.0 and MIT
License:        MPLv2.0 and MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE multistep/LICENSE.md
%doc CHANGELOG.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
