# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/scaleway/packer-plugin-scaleway
%global goipath         github.com/scaleway/packer-plugin-scaleway
Version:                1.0.4

%gometa

%global common_description %{expand:
Packer plugin for Scaleway Builder.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Packer plugin for Scaleway Builder

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/packer-plugin-scaleway %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
