# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/hashicorp/go-cty-funcs
%global goipath         github.com/hashicorp/go-cty-funcs
%global commit          2721b1e368400d56e5ade1763ae55ff2367897b5

%gometa

%global common_description %{expand:
Go-cty specific functions; mainly used in HCL2 templates.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Go-cty specific functions; mainly used in HCL2 templates

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
